### ISSUE TITLE
Create missing launch image

### ISSUE THREAD

**Issue by pinkiebell** [0xHabitat/landing-habitat#1]
@zschavi @MaxKuck :)

**Comment by MaxKaay** [comment]
a featured image right?

**Comment by MaxKaay** [comment]
![Featured Image - Habitat](https://user-images.githubusercontent.com/45236782/99081359-f76e0d80-25c2-11eb-9c7f-3d7091ac01f5.png)

an idea, see figma board (got rid of full caps in the title - seems less "hard")

**Comment by pinkiebell** [comment]
cool, done in 9437eb4
